###
# Создание категории
POST localhost:8081/categories
Content-Type: application/json

{
  "name": "Категория 1",
  "user": {
    "id": 1
  }
}

###
# Переименование категории
PUT localhost:8081/categories
Content-Type: application/json

{
  "id": 2,
  "name": "Переименование категории",
  "user": {
    "id": 1
  }
}



###
# Получение категории по id
GET localhost:8081/categories/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGaXJzdCIsImlhdCI6MTY4OTEwMTkwNiwiZXhwIjoxNjg5MTg4MzA2fQ.Lmm2QCMJxd0eYZIFikGzcd3OgRZqGwmduXYxDlftNpE

###
# Удаление категории по id
DELETE localhost:8081/categories?idCategory=1